backend:
  name: github
  repo: TheCeloReis/celoreis.dev

media_folder: public/images/uploads
public_folder: /images/uploads
site_domain: location.hostname

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    extension: "mdx"
    format: "frontmatter"
    create: true
    identifier_field: slug
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}}"
    i18n: true
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "text"
        i18n: true
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"
        i18n: true

  - name: "meta"
    label: "Meta"
    delete: false

    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"

      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

i18n:
  structure: multiple_folders
  locales: [en, pt, es]
  default_locale: en
