backend:
  name: github
  branch: master
  repo: TheCeloReis/celoreis.dev

media_folder: "images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{language}}-{{slug}}"
    fields:
      - label: "Language"
        name: "language"
        widget: "select"
        options:
          - { label: "English", value: "en" }
          - { label: "Spanish", value: "es" }
          - { label: "Portuguese", value: "pt" }
          - { label: "French", value: "fr" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
